/*
 * Offline support.
 *
 * Many students can only reach this site from campus, so it has to keep working
 * on a laptop with no connection — which is exactly when revision happens. A
 * student opens the site once while online and the browser keeps a complete
 * copy; after that every page, problem and example works with no network at all,
 * from the same URL, with saved progress intact.
 *
 * Strategy: serve from the cache immediately, and refresh the cache from the
 * network in the background. Pages therefore open instantly and work offline,
 * and a student who is online picks up new problems on their next visit. The
 * alternative — asking the network first — would make every page load wait for
 * a timeout on a bad connection, which is the common case here rather than the
 * rare one.
 *
 * The precache list below is generated. Run `node tools/build-sw.js` after
 * adding or removing a page; tools/test.js fails if it is stale.
 */

const CACHE_PREFIX = 'bsit-learning-lab-';
const RETIRED_CACHE_PREFIX = 'itcc47-practice-';
const CACHE = `${CACHE_PREFIX}v48`;

// --- precache:start (generated by tools/build-sw.js) ---
const PRECACHE = [
  './',
  'activity-catalog.js',
  'algorithms.js',
  'complexity.js',
  'computer-architecture-activities.js',
  'computer-architecture-machine.js',
  'computer-architecture-modules.html',
  'computer-architecture-practice-data.js',
  'computer-architecture-practice.html',
  'computer-architecture-practice.js',
  'computer-architecture.html',
  'course-catalog.js',
  'curriculum-ui.js',
  'curriculum.data.js',
  'curriculum.js',
  'editor-tools.js',
  'evaluation.js',
  'future-problems.js',
  'index.html',
  'industry-workbench.html',
  'industry-workbench.js',
  'instructor-access.js',
  'interpreter.js',
  'itcc45-activities.js',
  'itcc45-practice-data.js',
  'itcc45-practice.html',
  'itcc45-practice.js',
  'itcc45-topics.html',
  'itcc45-topics.js',
  'itcc45.html',
  'itcc47.html',
  'lesson.html',
  'linear-adt-activities.js',
  'nav.js',
  'playback.js',
  'practice.html',
  'presets.js',
  'problem-list.html',
  'problem-list.js',
  'problems-app.js',
  'problems-catalog.js',
  'problems.data.js',
  'problems.html',
  'recurrence.js',
  'release-profile.js',
  'sha256.js',
  'start-page.js',
  'student-materials.html',
  'styles.css',
  'sw-register.js',
  'symbolic-counting.js',
  'tooltip.js',
  'tracer-app.js',
  'tracer.html',
  'visualizer-app.js',
  'visualizer-progress.js',
  'visualizer-registry.js',
  'visualizer-workspace.css',
  'visualizer.html',
  'workspace-layout.js',
  'writer-app.js',
  'writer-checks.js',
  'writer-presets.js',
  'writer.html',
];
// --- precache:end ---

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Install atomically. A new worker must not activate with only part of the
    // practice shell available offline; the previous complete cache remains
    // active if any release asset is missing.
    await cache.addAll(PRECACHE);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((n) => (n.startsWith(CACHE_PREFIX) && n !== CACHE) || n.startsWith(RETIRED_CACHE_PREFIX))
      .map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;

  if (request.method !== 'GET') return;

  // Only this site. Anything cross-origin is left entirely alone.
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(request, { ignoreSearch: true });

    const fromNetwork = fetch(request)
      .then((response) => {
        if (response && response.ok && response.type === 'basic') {
          cache.put(request, response.clone());
        }
        return response;
      })
      .catch(() => null);

    if (cached) {
      // Refresh in the background; the student gets the cached copy now.
      event.waitUntil(fromNetwork);
      return cached;
    }

    const response = await fromNetwork;
    if (response) return response;

    // Offline, and this exact URL was never stored. A page request can still
    // be satisfied by the home page rather than the browser's error screen.
    if (request.mode === 'navigate') {
      const home = await cache.match('./') || await cache.match('index.html');
      if (home) return home;
    }

    return new Response(
      'You are offline and this page has not been saved yet.\n\n' +
      'Open the site once while you have a connection, then it will work without one.',
      { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } }
    );
  })());
});
