/*
 * Offline support.
 *
 * Many students can only reach this site from campus, so it has to keep working
 * on a laptop with no connection — which is exactly when revision happens. A
 * student opens the site once while online and the browser keeps a complete
 * copy; after that every page, problem and example works with no network at all,
 * from the same URL, with saved progress intact.
 *
 * Strategy: serve from the cache immediately, and refresh the cache from the
 * network in the background. Pages therefore open instantly and work offline,
 * and a student who is online picks up new problems on their next visit. The
 * alternative — asking the network first — would make every page load wait for
 * a timeout on a bad connection, which is the common case here rather than the
 * rare one.
 *
 * The precache list below is generated. Run `node tools/build-sw.js` after
 * adding or removing a page; tools/test.js fails if it is stale.
 */

const CACHE = 'itcc47-offline';

// --- precache:start (generated by tools/build-sw.js) ---
const PRECACHE = [
  './',
  'algorithms.js',
  'app.js',
  'complexity.js',
  'index.html',
  'interpreter.js',
  'presets.js',
  'problems-app.js',
  'problems.data.js',
  'problems.html',
  'sha256.js',
  'styles.css',
  'sw-register.js',
  'tooltip.js',
  'tracer-app.js',
  'tracer.html',
  'writer-app.js',
  'writer-checks.js',
  'writer-presets.js',
  'writer.html',
];
// --- precache:end ---

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Individually, so one missing file cannot fail the whole install and
    // leave the student with no offline copy at all.
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const res = await fetch(url, { cache: 'reload' });
        if (res && res.ok) await cache.put(url, res);
      } catch (e) { /* skipped; the fetch handler will cache it on first use */ }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;

  if (request.method !== 'GET') return;

  // Only this site. Anything cross-origin is left entirely alone.
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(request, { ignoreSearch: true });

    const fromNetwork = fetch(request)
      .then((response) => {
        if (response && response.ok && response.type === 'basic') {
          cache.put(request, response.clone());
        }
        return response;
      })
      .catch(() => null);

    if (cached) {
      // Refresh in the background; the student gets the cached copy now.
      event.waitUntil(fromNetwork);
      return cached;
    }

    const response = await fromNetwork;
    if (response) return response;

    // Offline, and this exact URL was never stored. A page request can still
    // be satisfied by the home page rather than the browser's error screen.
    if (request.mode === 'navigate') {
      const home = await cache.match('./') || await cache.match('index.html');
      if (home) return home;
    }

    return new Response(
      'You are offline and this page has not been saved yet.\n\n' +
      'Open the site once while you have a connection, then it will work without one.',
      { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } }
    );
  })());
});
