/* Plain-language algorithms from Topic 01, including the deliberately flawed ones. */

const WRITER_PRESETS = [
  {
    name: 'Library Fine — corrected (Algorithm 1-4)',
    steps: [
      { text: 'Read the number of overdue days', level: 0 },
      { text: 'Read whether the book is lost', level: 0 },
      { text: 'Read whether the student is a library member', level: 0 },
      { text: 'If the number of overdue days is negative, display "INVALID"', level: 0 },
      { text: 'Otherwise, if the book is lost, display 500', level: 0 },
      { text: 'Otherwise:', level: 0 },
      { text: 'Set fine to overdue days times 10', level: 1 },
      { text: 'If fine is greater than 300, set fine to 300', level: 1 },
      { text: 'If the student is a library member, subtract 20 from fine', level: 1 },
      { text: 'If fine is less than 0, set fine to 0', level: 1 },
      { text: 'Display fine', level: 1 },
    ],
  },
  {
    name: 'Library Fine — wrong order (Algorithm 1-3)',
    steps: [
      { text: 'Read the number of overdue days', level: 0 },
      { text: 'Read whether the book is lost', level: 0 },
      { text: 'Read whether the student is a library member', level: 0 },
      { text: 'Set fine to overdue days times 10', level: 0 },
      { text: 'If the student is a library member, subtract 20 from fine', level: 0 },
      { text: 'If fine is greater than 300, set fine to 300', level: 0 },
      { text: 'If the book is lost, set fine to 500', level: 0 },
      { text: 'If fine is less than 0, set fine to 0', level: 0 },
      { text: 'If the number of overdue days is negative, display "INVALID"', level: 0 },
      { text: 'Otherwise, display fine', level: 0 },
    ],
  },
  {
    name: 'Delivery rules as the owner said them',
    steps: [
      { text: 'Read the distance', level: 0 },
      { text: 'Read whether the customer is premium', level: 0 },
      { text: 'If the customer is close, charge a 30 delivery fee', level: 0 },
      { text: 'If the customer is within a manageable area, charge a 50 delivery fee', level: 0 },
      { text: 'If the customer is very far, charge an 80 delivery fee', level: 0 },
      { text: 'If the distance is 0 or negative, do not proceed', level: 0 },
      { text: 'Premium customers receive a 10 discount on the delivery fee', level: 0 },
    ],
  },
  {
    name: 'Reward Points, with a loop (Algorithm 1-6)',
    steps: [
      { text: 'Read the number of purchases', level: 0 },
      { text: 'Read whether the customer is a member', level: 0 },
      { text: 'Set the total purchase amount to 0', level: 0 },
      { text: 'Set the reward points to 0', level: 0 },
      { text: 'Set the invalid purchase count to 0', level: 0 },
      { text: 'For each purchase:', level: 0 },
      { text: 'Read the purchase amount', level: 1 },
      { text: 'If the amount is 0 or negative, increase the invalid purchase count by 1', level: 1 },
      { text: 'Otherwise:', level: 1 },
      { text: 'Add the amount to the total', level: 2 },
      { text: 'If the amount is 1000 or more, add 50 points', level: 2 },
      { text: 'Otherwise, if the amount is 500 or more, add 20 points', level: 2 },
      { text: 'Otherwise, add 5 points', level: 2 },
      { text: 'If the customer is a member, add 10 points', level: 2 },
      { text: 'If the total is 3000 or more, add 100 bonus points', level: 0 },
      { text: 'Display the total purchase amount', level: 0 },
      { text: 'Display the reward points', level: 0 },
      { text: 'Display the invalid purchase count', level: 0 },
    ],
  },
  {
    name: 'Blank',
    steps: [{ text: '', level: 0 }],
  },
];
