const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const { spawnSync } = require('child_process');
const { findPython } = require('../tools/python-runtime');
const { root, fixture, preview, open, surface, seek, screenshot } = require('./recursion-helpers');

// Trusted faults are generated by real Python and mounted through the same pack
// response as the normal fixtures. No second renderer or execution state is used.
function faultPack(kind) {
  const [python, prefix] = findPython();
  const code = [
    'import json, sys',
    'sys.path.insert(0, "tools/recursion")',
    'from build_traces import fixture_source, generate',
    'source = fixture_source("sum_to", 3)',
    kind === 'limit' ? 'source = source.replace("sum_to(n - 1)", "sum_to(n)")'
      : 'source = source.replace("return total", "print(total)")',
    'print(json.dumps(generate("sum_to", source, "sum_to:n3")))',
  ].join('\n');
  const run = spawnSync(python, [...prefix, '-B', '-c', code], { cwd: root, encoding: 'utf8', timeout: 10000 });
  if (run.error || run.status !== 0) throw run.error || new Error(run.stderr);
  const data = JSON.parse(run.stdout);
  const context = vm.createContext({});
  vm.runInContext(fs.readFileSync(path.join(root, 'activity-packs/recursion-traces.js'), 'utf8'), context);
  const pack = vm.runInContext('ITCC47RecursionTraces', context);
  pack.fixtures['sum_to:n3'] = data;
  return { data, source: 'const ITCC47RecursionTraces = ' + JSON.stringify(pack) + ';' };
}

test.describe('M5 presentation ownership', () => {
  test.beforeEach(async ({ page }) => {
    await preview(page);
    if (process.env.M5_REFERENCE_DESKTOP) await page.setViewportSize({ width: 1920, height: 1080 });
  });

  for (const [id, program] of [['recursion-call-stack', 'countdown'], ['recursion-return-values', 'sum_to']]) {
    test('caller instruction belongs to the waiting caller: ' + program, async ({ page }, testInfo) => {
      test.setTimeout(60000);
      const errors = [];
      page.on('pageerror', error => errors.push(error.message));
      await open(page, id);
      for (const n of [0, 1, 3, 5]) {
        await page.getByLabel('Python fixture', { exact: true }).selectOption(String(n));
        const data = fixture(program, n);
        for (const [index, event] of data.events.entries()) {
          if (event.eventKind !== 'RETURN_COMPLETE' || !event.frame.stack.length) continue;
          await seek(page, data, index);
          await surface(page, 'Executing');
          const caller = event.frame.framesById[event.frame.stack[0]];
          if (n === 3) await screenshot(page, testInfo, 'presentation-' + program + '-handoff-' + index);
          expect.soft(await page.locator('.recursion-now-line > span').innerText()).toMatch(new RegExp('line ' + caller.suspendedCallSite + '$', 'i'));
          expect.soft(await page.locator('.recursion-now-line code').innerText()).toBe(data.source.split('\n')[caller.suspendedCallSite - 1].trim());
          expect.soft(await page.locator('.source-line.is-current > span').textContent()).toBe(String(event.source.line));
          expect.soft(await page.locator('.recursion-workspace').getAttribute('data-active-call')).toBe('');
        }
      }
      expect(errors).toEqual([]);
    });

    test('completion follows driver; explicit history stays historical: ' + program, async ({ page }, testInfo) => {
      for (const n of [0, 1, 3, 5]) {
        await open(page, id);
        await page.getByLabel('Python fixture', { exact: true }).selectOption(String(n));
        const data = fixture(program, n);
        await seek(page, data, data.events.length - 1);
        await surface(page, 'Executing');
        if (n === 3) await screenshot(page, testInfo, 'presentation-' + program + '-complete');
        expect.soft(await page.locator('.recursion-inspector').innerText()).toContain('Driver complete');
        expect.soft(await page.locator('.recursion-executing-title').count()).toBe(0);
        await page.locator('.recursion-evidence > summary').click();
        await page.locator('.recursion-history button').last().click();
        expect.soft(await page.locator('.recursion-inspector').innerText()).toContain('Completed call · history');
        await expect(page.locator('.recursion-workspace')).toHaveAttribute('data-event-id', data.events.at(-1).eventId);
        await expect(page.locator('.source-line.is-current')).toHaveCount(0);
        await expect(page.locator('[data-call-id]')).toHaveCount(0);
        expect(await page.locator('[data-recursion-stdout]').textContent()).toBe(data.events.at(-1).frame.stdout);
        if (n === 3) await screenshot(page, testInfo, 'presentation-' + program + '-history');
      }
    });
  }

  for (const kind of ['error', 'limit']) {
    test('stopped snapshots do not imply return handoff: ' + kind, async ({ page }, testInfo) => {
      const { data, source } = faultPack(kind);
      await page.route('**/activity-packs/recursion-traces.js', route => route.fulfill({ contentType: 'application/javascript', body: source }));
      await open(page, 'recursion-return-values');
      await seek(page, data, data.events.length - 1);
      await surface(page, 'Executing');
      await screenshot(page, testInfo, 'presentation-stopped-' + kind);
      const text = await page.locator('.recursion-inspector').innerText();
      expect.soft(text).not.toContain('receiving a result');
      expect.soft(text).toContain('Stopped execution');
      expect.soft(await page.locator('.recursion-stack').innerText()).not.toContain('Running its own code');
      await expect(page.locator('[data-driver-answer]')).toHaveAttribute('data-value-kind', 'UNBOUND');
      expect(await page.locator('[data-recursion-stdout]').textContent()).toBe(kind === 'error' ? '1\n' : '');
      await expect(page.locator('.recursion-workspace')).toHaveAttribute('data-active-call', '');
    });
  }
});
