/*
 * Regenerates the precache list inside sw.js.
 *
 *   node tools/build-sw.js
 *
 * The service worker has to name every file it wants available offline. Keeping
 * that list by hand means a page added later is silently missing when a student
 * has no connection — which they would only discover at the worst moment. So
 * the list is generated from what is actually in the folder, and tools/test.js
 * fails if sw.js has drifted out of date.
 *
 * Only the student-facing app is included. tools/ and setup/ are not part of
 * what needs to work on a bus with no signal.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SW = path.join(ROOT, 'sw.js');

const START = '// --- precache:start (generated by tools/build-sw.js) ---';
const END = '// --- precache:end ---';

// Files that are part of the worker's own machinery, not the app it caches.
const EXCLUDE = new Set(['sw.js']);

/** The shipped app: every page, plus the styles and scripts they load. */
function collectAssets() {
  const entries = fs.readdirSync(ROOT, { withFileTypes: true })
    .filter((e) => e.isFile())
    .map((e) => e.name)
    .filter((name) => /\.(html|css|js)$/.test(name))
    .filter((name) => !EXCLUDE.has(name))
    .sort();

  // './' is what a visit to the site root actually requests. Without it, the
  // bare URL misses the cache offline even though index.html is stored.
  return ['./', ...entries];
}

function build() {
  if (!fs.existsSync(SW)) {
    console.error('Missing sw.js — nothing to update.');
    process.exit(1);
  }

  const assets = collectAssets();
  const source = fs.readFileSync(SW, 'utf8');

  const startIdx = source.indexOf(START);
  const endIdx = source.indexOf(END);
  if (startIdx === -1 || endIdx === -1) {
    console.error('sw.js is missing its precache markers. Restore them and run again.');
    process.exit(1);
  }

  const list = assets.map((a) => `  '${a}',`).join('\n');
  const replacement = `${START}\nconst PRECACHE = [\n${list}\n];\n${END}`;
  const updated = source.slice(0, startIdx) + replacement + source.slice(endIdx + END.length);

  if (updated === source) {
    console.log(`sw.js already up to date (${assets.length} entries).`);
    return;
  }

  fs.writeFileSync(SW, updated, 'utf8');
  console.log(`Updated sw.js precache list — ${assets.length} entries:`);
  assets.forEach((a) => console.log('  ' + a));
}

/** Shared with tools/test.js so the check and the generator cannot disagree. */
function expectedAssets() {
  return collectAssets();
}

if (require.main === module) build();

module.exports = { expectedAssets, START, END };
